"""empty message

Revision ID: 29d51648411e
Revises: 
Create Date: 2024-03-18 01:31:47.567039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d51648411e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_item_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_unit'), ['unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_unit_price'), ['unit_price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_unit_price'))
        batch_op.drop_index(batch_op.f('ix_item_unit'))
        batch_op.drop_index(batch_op.f('ix_item_quantity'))
        batch_op.drop_index(batch_op.f('ix_item_name'))

    op.drop_table('item')
    # ### end Alembic commands ###
