"""empty message

Revision ID: 301fc9acaadd
Revises: 162782be5a7c
Create Date: 2024-03-18 10:51:35.298013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301fc9acaadd'
down_revision = '162782be5a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_index'), ['index'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_item_quantity_in_stock'), ['quantity_in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_quantity_sold'), ['quantity_sold'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_unit'), ['unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_unit_price'), ['unit_price'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('ix_product_index')
        batch_op.drop_index('ix_product_name')
        batch_op.drop_index('ix_product_quantity_in_stock')
        batch_op.drop_index('ix_product_quantity_sold')
        batch_op.drop_index('ix_product_unit')
        batch_op.drop_index('ix_product_unit_price')

    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('quantity_in_stock', sa.INTEGER(), nullable=True),
    sa.Column('quantity_sold', sa.INTEGER(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=100), nullable=True),
    sa.Column('unit_price', sa.INTEGER(), nullable=True),
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('ix_product_unit_price', ['unit_price'], unique=False)
        batch_op.create_index('ix_product_unit', ['unit'], unique=False)
        batch_op.create_index('ix_product_quantity_sold', ['quantity_sold'], unique=False)
        batch_op.create_index('ix_product_quantity_in_stock', ['quantity_in_stock'], unique=False)
        batch_op.create_index('ix_product_name', ['name'], unique=1)
        batch_op.create_index('ix_product_index', ['index'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_unit_price'))
        batch_op.drop_index(batch_op.f('ix_item_unit'))
        batch_op.drop_index(batch_op.f('ix_item_quantity_sold'))
        batch_op.drop_index(batch_op.f('ix_item_quantity_in_stock'))
        batch_op.drop_index(batch_op.f('ix_item_name'))
        batch_op.drop_index(batch_op.f('ix_item_index'))

    op.drop_table('item')
    # ### end Alembic commands ###
