"""empty message

Revision ID: 58b11244c611
Revises: 29d51648411e
Create Date: 2024-03-18 02:03:10.436031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b11244c611'
down_revision = '29d51648411e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_item_index'), ['index'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_index'))
        batch_op.drop_column('index')

    # ### end Alembic commands ###
