"""empty message

Revision ID: 73b6aa469bec
Revises: 58b11244c611
Create Date: 2024-03-18 02:57:00.362614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b6aa469bec'
down_revision = '58b11244c611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sold', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sold_index'), ['index'], unique=False)
        batch_op.create_index(batch_op.f('ix_sold_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_sold_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_sold_unit'), ['unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_sold_unit_price'), ['unit_price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sold_unit_price'))
        batch_op.drop_index(batch_op.f('ix_sold_unit'))
        batch_op.drop_index(batch_op.f('ix_sold_quantity'))
        batch_op.drop_index(batch_op.f('ix_sold_name'))
        batch_op.drop_index(batch_op.f('ix_sold_index'))

    op.drop_table('sold')
    # ### end Alembic commands ###
